apiVersion: v1
kind: Pod
metadata: 
  name: pod-secret-as-volume
spec: 
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secret-volume
  volumes:
    - name: secret-volume
      secret: 
        secretName: test-secret
