apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-as-env-var
spec: 
  containers:
  - name: nginx-container
    image: nginx
    env: 
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: backend-user
          key: backend-username

